#pragma once
#include "bootstrap/instances/Part.h"
#include "bootstrap/instances/MeshPart.h"
#include "bootstrap/instances/Model.h"
#include "bootstrap/instances/Folder.h"
#include "bootstrap/instances/CameraGame.h"
#include "bootstrap/instances/Workspace.h"
#include "bootstrap/instances/Script.h"
#include "bootstrap/instances/LocalScript.h"
#include "bootstrap/instances/Sky.h"
// #include "bootstrap/instances/ModuleScript.h"
