name: Build MoonEngine

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PROJECT_ROOT: .
  BUILD_DIR: build
  DIST_DIR: dist
  CMAKE_PREFIX_PATH: third_party/vendor

jobs:
  build-windows:
    runs-on: windows-latest

    # The 'strategy: matrix' block has been removed.
    # We now hardcode the build_type to Release.

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Configure CMake (Release)
        run: |
          cmake . -B ${{ env.BUILD_DIR }} -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="${{ env.CMAKE_PREFIX_PATH }}"

      - name: Build (Release)
        run: |
          cmake --build ${{ env.BUILD_DIR }} --config Release --parallel

      - name: Install
        run: |
          cmake --install ${{ env.BUILD_DIR }} --prefix ${{ env.DIST_DIR }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MoonEngine-Windows-Release
          path: ${{ env.DIST_DIR }}
